### PR TITLE
add push notifications

### PR DESCRIPTION
**Pull request by brortao**
the redis queue may seem like a lot but i don't think the backend will be production-ready without it. curious to hear thoughts.

### CODE REVIEW

**Comment by brortao** [comment]
two issues:
* not sure how to test this
* tests fail sometimes due to an async job. not sure what's causing it.

**Comment by brortao** [comment]
the tests fail (but inconsistently) due to some async job. i think it's the redis queue, since that's the only change i can think would cause it, but i don't know why since i'm making sure to stop it.

@runranron and @chrisdevereux, i'd be curious to hear your intuitions on how to resolve this because i'm a bit stumped :)

**Comment by chrisdevereux** [comment]
agree that we'll need redis for this before v1.0. Although if it turns out to be a huge pain to get it working w/ tests, I'd be in favour of removing it until we're actually near a point where we might need to scale.

re: these sporadic test failures.... you mean [these ones](https://travis-ci.com/Wobbly-App/graphql-backend/builds/104974678)? it looks like maybe an exception is being thrown when the expo server is being imported and the queues set up?? it looks like none of the tests are ever actually run, which suggests to me some kind of error setting the tests up

about testing this, I think there are probly two things to consider:
* re: testing the stuff in `communications/notifications.ts`...  I think the best thing to do here is to split it into two modules...
    1) a client module that provides a thin wrapper around 'expo-server-sdk' and has an integration test ensuring that we're calling it correctly (eg. not getting 400 responses back from our API calls)
    2) a service module that should be responsible for polling for notification responses, tested using a mocked version of the client that simulates the various responses we get back from expo
* re: testing stuff that uses `communications/notifications.ts`... from their perspective, it's pretty much fire & forget, so it should be sufficient to just use jest's [auto-mocking feature](https://jestjs.io/docs/en/jest-object.html#jestmockmodulename-factory-options) feature the mock out the service module to stop it actually calling into all that infrastructure

**Comment by brortao** [comment]
@chrisdevereux i "fixed" the failing tests by adding `--forxeExit` to our jest command. feels hacky but i don't know just how bad that is.

good ideas re: testing! i'll try it out.

**Comment by brortao** [comment]
one note re: testing the expo client...

we can't actually send requests to expo without a real device to receive the push notification. if we try, we'll get `DeviceNotRegistered` errors.

**Pull request merged**
